disabled_rules: # rule identifiers to exclude from running
  - comment_spacing
  - trailing_whitespace
  - todo
  - large_tuple
  - inclusive_language

opt_in_rules:
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - empty_xctest_method
  - explicit_init
  - file_name
  - first_where
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - strong_iboutlet
  - toggle_bool
  - vertical_parameter_alignment_on_call
  - void_return
  - yoda_condition

excluded:
  - fastlane
  - SourcePackages
  - .build
  - "**/Generated/*.swift"
  - "**/Mocks/*.swift"
  - "**/DI/*+Injection.swift"
  - "**/Defaults/*+DefaultsKeys.swift"

line_length:
  warning: 160

custom_rules:
  sf_safe_symbol:
    name: "Safe SFSymbol"
    message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
    regex: "(Image\\(systemName:)|(NSImage\\(symbolName:)|(Label[^,]+?,\\s*systemImage:)|(UIApplicationShortcutIcon\\(systemImageName:)"
    severity: warning
