//
//  String+Extensions.swift
//  FilmFinder
//
//  Created by Daniel Klinge on 16/09/2024.
//

import Foundation
import UIKit

public extension String {
    
    /// Returns localized string using `self` as a key.
    /// - Parameters:
    ///   - tableName: Localization table name. Default is `nil`.
    ///   - defaultValue: Default value to return if localized string is not found. Default is `self`.
    /// - Note: Localization files are owned and constants file is generated by `GeminiX` project.
    ///     However, to make localization constaints to be available globally to all modules at compile time
    ///     it is put into `KevinCore`.
    func localized(tableName: String? = nil, defaultValue: String? = nil) -> String {
        let value: String
        
        // NOTE: Localization doesn't work in Unit Tests and SwiftUI previews in modules,
        // thefore we use provided default value, which is expected to be an English translation
        // coming from autogenerated localization constants.
        if UIDevice.isSwiftUIPreview || UIDevice.isUnitTest {
            value = defaultValue ?? self
            
        // Ignore default value and use `key` instead to make it apparent that localization is missing.
        } else {
            value = self
        }
        
        return NSLocalizedString(self, tableName: tableName, value: value, comment: "")
    }
}
